version: 2.1
commands: 
  install-deps:
    steps:
      - run: 
          name: Install Dependencies
          command: | 
            npm ci
jobs: 
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout 
      - install-deps
workflows:
    build-and-package:
      jobs:
        - ci-build